apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-06-09T10:38:36Z"
  name: my-pod
  namespace: default
  resourceVersion: "10432"
  uid: 83b37ad7-79b3-46b7-856f-d3f72d60a7d4
spec:
  containers:
  - image: nginx:1.19.2
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-855xn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: my-cluster-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-855xn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-06-09T10:38:37Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-06-09T10:38:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-06-09T10:38:37Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-06-09T10:38:37Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-06-09T10:38:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://841de1b4dfdb43bb7ba8468ae9837cba0620807ea11411e8ab809bc0afdc5262
    image: docker.io/library/nginx:1.19.2
    imageID: docker.io/library/nginx@sha256:c628b67d21744fce822d22fdcc0389f6bd763daac23a6b77147d0712ea7102d0
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-06-09T10:38:37Z"
  hostIP: 172.18.0.5
  hostIPs:
  - ip: 172.18.0.5
  phase: Running
  podIP: 10.244.3.251
  podIPs:
  - ip: 10.244.3.251
  qosClass: BestEffort
  startTime: "2026-06-09T10:38:36Z"
